/**************************************************************************************************
  Filename:       zcl_config.h

  Description: - sample app template file

  Copyright 2006-2014 Texas Instruments Incorporated. All rights reserved.

  IMPORTANT: Your use of this Software is limited to those specific rights
  granted under the terms of a software license agreement between the user
  who downloaded the software, his/her employer (which must be your employer)
  and Texas Instruments Incorporated (the "License").  You may not use this
  Software unless you agree to abide by the terms of the License. The License
  limits your use, and you acknowledge, that the Software may not be modified,
  copied or distributed unless embedded on a Texas Instruments microcontroller
  or used solely and exclusively in conjunction with a Texas Instruments radio
  frequency transceiver, which is integrated into your product.  Other than for
  the foregoing purpose, you may not use, reproduce, copy, prepare derivative
  works of, modify, distribute, perform, display or sell this Software and/or
  its documentation for any purpose.

  YOU FURTHER ACKNOWLEDGE AND AGREE THAT THE SOFTWARE AND DOCUMENTATION ARE
  PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
  INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, TITLE,
  NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL
  TEXAS INSTRUMENTS OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER CONTRACT,
  NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR OTHER
  LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
  INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE
  OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT
  OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
  (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.

  Should you have any questions regarding your right to use this Software,
  contact Texas Instruments Incorporated at www.TI.com.
**************************************************************************************************/

/**************************************************************************************************
 DO NOT EDIT
 DO NOT EDIT
 DO NOT EDIT - This file was generated by the SysConfig tool.
 DO NOT EDIT
 DO NOT EDIT
**************************************************************************************************/

#ifndef ZCL_CONFIG_H
#define ZCL_CONFIG_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined (__IAR_SYSTEMS_ICC__)
#define WEAK __weak
#elif defined (__TI_COMPILER_VERSION) || defined (__TI_COMPILER_VERSION__) || defined (__clang__)
#define WEAK __attribute__((weak))
#endif



// zcl_*.h #includes
#include "ti_zstack_config.h"
#include "zcl_datatypes.h"
#include "zcl_port.h"
#include "zcl.h"
#include "zcl_ha.h"

#include "zcl_ha.h"
#include "zcl_general.h"


/*********************************************************************
 * Application Globals
 *********************************************************************/
extern uint8_t sampleApp_serviceTaskId;


/*********************************************************************
 * ZCL Attribute Variables
 *********************************************************************/

// Basic Cluster (Server-Side)
extern uint8 fanbee_Basic_ZCLVersion;
extern enum8 fanbee_Basic_PowerSource;
extern uint16 fanbee_Basic_ClusterRevision;
extern uint8 fanbee_Basic_ApplicationVersion;
extern uint8 fanbee_Basic_ManufacturerName[];
extern uint8 fanbee_Basic_ModelIdentifier[];

// Identify Cluster (Server-Side)
extern uint16 fanbee_Identify_IdentifyTime;
extern uint16 fanbee_Identify_ClusterRevision;

// Groups Cluster (Server-Side)
extern map8 fanbee_Groups_NameSupport;
extern uint16 fanbee_Groups_ClusterRevision;

// Scenes Cluster (Server-Side)
extern uint8 fanbee_Scenes_SceneCount;
extern uint8 fanbee_Scenes_CurrentScene;
extern SGroupId fanbee_Scenes_CurrentGroup;
extern bool fanbee_Scenes_SceneValid;
extern map8 fanbee_Scenes_NameSupport;
extern uint16 fanbee_Scenes_ClusterRevision;

// OnOff Cluster (Server-Side)
extern bool fanbee_OnOff_OnOff;
extern uint16 fanbee_OnOff_ClusterRevision;

// Level Cluster (Server-Side)
extern uint8 fanbee_Level_CurrentLevel;
extern uint16 fanbee_Level_ClusterRevision;
extern uint8 fanbee_Level_MinLevel;
extern uint8 fanbee_Level_MaxLevel;


/*********************************************************************
 * ZCL Attribute List
 *********************************************************************/
extern const zclAttrRec_t fanbee_Attrs[];
extern const uint8_t fanbee_zclAttrsArraySize;


/*********************************************************************
 * ZCL Attribute Default Values (const)
 *********************************************************************/
extern const uint8 DEFAULT_BASIC_ZCL_VERSION ;
extern const enum8 DEFAULT_BASIC_POWER_SOURCE ;
extern const uint16 DEFAULT_BASIC_CLUSTER_REVISION;
extern const uint8 DEFAULT_BASIC_APPLICATION_VERSION ;
extern const uint16 DEFAULT_IDENTIFY_IDENTIFY_TIME ;
extern const uint16 DEFAULT_IDENTIFY_CLUSTER_REVISION;
extern const uint16 DEFAULT_GROUPS_CLUSTER_REVISION;
extern const uint8 DEFAULT_SCENES_SCENE_COUNT ;
extern const uint8 DEFAULT_SCENES_CURRENT_SCENE ;
extern const SGroupId DEFAULT_SCENES_CURRENT_GROUP ;
extern const bool DEFAULT_SCENES_SCENE_VALID ;
extern const uint16 DEFAULT_SCENES_CLUSTER_REVISION;
extern const bool DEFAULT_ON_OFF_ON_OFF ;
extern const uint16 DEFAULT_ONOFF_CLUSTER_REVISION;
extern const uint8 DEFAULT_LEVEL_CURRENT_LEVEL ;
extern const uint16 DEFAULT_LEVEL_CLUSTER_REVISION;
extern const uint8 DEFAULT_LEVEL_MIN_LEVEL ;
extern const uint8 DEFAULT_LEVEL_MAX_LEVEL ;

/*********************************************************************
 * ZCL Attribute Reset Functionality
 *********************************************************************/
extern void fanbee_ResetAttributesToDefaultValues(void);


/*********************************************************************
 * ZCL Commands List
 *********************************************************************/
extern const zclCommandRec_t fanbee_Cmds[];
extern const uint8_t fanbee_zclCmdsArraySize;



/*********************************************************************
 * ZCL Command Callback Structs
 *********************************************************************/
extern zclGeneral_AppCallbacks_t fanbee_zclGeneralCmdCallbacks;


/*********************************************************************
 * ZCL Command Callbacks
 *********************************************************************/

/* GENERAL */
extern void fanbee_IdentifyCB( zclIdentify_t *pCmd );
extern void fanbee_IdentifyQueryCB( zclIdentifyQuery_t *pCmd );
extern void fanbee_OnOffCB( uint8_t cmd );
extern void fanbee_LevelControlMoveToLevelCB( zclLCMoveToLevel_t *pCmd );
extern void fanbee_LevelControlMoveCB( zclLCMove_t *pCmd );
extern void fanbee_LevelControlStepCB( zclLCStep_t *pCmd );
extern void fanbee_LevelControlStopCB( zclLCStop_t *pCmd );
extern uint8_t fanbee_SceneStoreReqCB( zclSceneReq_t *pReq );
extern void fanbee_SceneRecallReqCB( zclSceneReq_t *pReq );

/*********************************************************************
 * Simple Descriptor
 *********************************************************************/
#define FANBEE_ENDPOINT				8
#define FANBEE_DEVICE_VERSION		1
#define FANBEE_FLAGS					0
extern const cId_t fanbee_InClusterList[];
extern const cId_t fanbee_OutClusterList[];
extern SimpleDescriptionFormat_t fanbee_SimpleDesc;


/*********************************************************************
 * ZCL Initialization Hooks
 *********************************************************************/
extern void zclConfigInit(void);



/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* ZCL_CONFIG_H */
